name: Actualiza IPTV
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -L "https://raw.githubusercontent.com/Ignac16/Iptv-spain-m3u-1416/main/playlist_spain.m3u8" -o lista.m3u
      - run: |
          git config user.name "hamotero"
          git config user.email "hamotero@users.noreply.github.com"
          git add lista.m3u
          git commit -m "actualiza" || true
          git push
